test:
	node test-runner.js

generate:
	node test-runner.js -o

server:
	java -jar bin/selenium-server-standalone-2.47.0.jar

clean:
	rm -rf screenshots/originals/*.png
	rm -rf screenshots/fails/*.png
	rm -rf screenshots/tmp/*.png
